spring:
  banner:
    location: file:./banner.txt

site:
  datasource_driver: com.mysql.cj.jdbc.Driver
  datasource_url: jdbc:mysql://localhost:3306/lckclub?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  datasource_username: root
  datasource_password: Zyy150824.

# 想看mybatis执行的sql的时候，去掉下面这段的注释
#logging:
#  level:
#    co:
#      yiiu:
#        lckclub:
#          mapper: debug
