[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="sec" type="com.lckclub.config.ShiroTag" --]
[#-- @ftlvariable name="model" type="com.lckclub.util.BaseModel" --]
[#-- @ftlvariable name="page" type="com.lckclub.util.MyPage" --]
[#-- @ftlvariable name="i18n" type="com.lckclub.util.LocaleMessageSourceUtil" --]
